#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run Redis server.
#======================================================================================================================

bf-echo "Starting Redis server."
s6-setuidgid redis exec redis-server ${REDIS_CONFIG}
