#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate Redis configuration file.
#======================================================================================================================

# generate config from the template
bf-echo "Generating ${REDIS_CONFIG}."
bf-esh ${BF_TEMPLATES}/redis.conf.esh ${REDIS_CONFIG}
bf-ch -o redis:redis -m 0400 -t f ${REDIS_CONFIG}
