#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "REDIS_DATA" "/data"
bg-env "REDIS_CONFIG" "/etc/redis.conf"
