#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate Redis configuration file.
#======================================================================================================================

# generate config from the template
bf-debug "Generating ${REDIS_CONFIG}."
esh -o ${REDIS_CONFIG} \
    ${BF_TEMPLATES}/redis.conf.esh

bf-fix-attrs
