name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read Redis version - major
        uses: bfren/read-file-action@v1
        with:
          path: ./REDIS_MAJOR
        id: redis_major
      -
        name: Read Redis version - minor
        uses: bfren/read-file-action@v1
        with:
          path: ./REDIS_MINOR
        id: redis_minor
      -
        name: Read Redis version - revision
        uses: bfren/read-file-action@v1
        with:
          path: ./REDIS_REVISION
        id: redis_revision
      -
        name: Read image version
        uses: bfren/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/redis:latest
            bfren/redis:${{ steps.version.outputs.content }}
            bfren/redis:redis${{ steps.redis_major.outputs.content }}
            bfren/redis:redis${{ steps.redis_major.outputs.content }}-${{ steps.version.outputs.content }}
            bfren/redis:redis${{ steps.redis_minor.outputs.content }}
            bfren/redis:redis${{ steps.redis_minor.outputs.content }}-${{ steps.version.outputs.content }}
            bfren/redis:redis${{ steps.redis_revision.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
